### ISSUE TITLE
Project cleanup

### ISSUE THREAD

**Issue by KrystianOg** [NirajD10/pureplantparadise#2]
We want a fresh start, make sure environment is ready to be setup

just rm -rf everthing (excluding .git directory and maybe some other hidden directories)

create new branch out of `monorepo` then make a pr targeting `monorepo`, later on we'll refactor some features

**Comment by NirajD10** [comment]
Project cleanup is finished from `monorepo` branch and created new branch called `monorepo-branch1` under `monorepo` branch
