### ISSUE TITLE
Initial project setup

### ISSUE THREAD

**Issue by KrystianOg** [NirajD10/pureplantparadise#3]
1. Create a [pnpm workspace](https://pnpm.io/workspaces)
the pnpm-workspace file should like this
```yaml
# pnpm-workspace.yaml
packages:
  # executable/launchable applications
  - 'apps/*'
  # all packages in subdirs of packages/ and components/
  - 'packages/*'
```
for now packages directtory will be empty, you may want to create the directory now for later use, by default git won't track it, to avoid this create empty .gitkeep file inside `packages` directory

2. initialize projects

- frontend `pnpm create vite frontend --template react-ts`, if you don't have pnpm `npm i -g pnpm`
- backend `mkdir backend && cd backend` then `pnpm init`, then install packages as before `pnpm add express` and ts declarations `pnpm add -D @types/express`

**Comment by NirajD10** [comment]
The setup is finished.

**Comment by NirajD10** [comment]
Wrong placed fronted and backend folder on package. So I will update to these folder to apps.

**Comment by NirajD10** [comment]
I did finalized changes.
