### ISSUE TITLE
Regarding Admin Dashboard

### ISSUE THREAD

**Issue by dipesh-17** [NirajD10/pureplantparadise#6]
**NirajD10 Sir still I'm facing this issue when I enter the admin credential it redirects to the admin dashboard page but it's not opening all other pages are working except this page.**

![image](https://github.com/NirajD10/pureplantparadise/assets/75944150/adf7ecc0-6487-4940-806f-cd5a9db74b45)

![image](https://github.com/NirajD10/pureplantparadise/assets/75944150/4e34b4ec-fed5-4c22-bf51-196b9b692bb1)

![image](https://github.com/NirajD10/pureplantparadise/assets/75944150/b31caf3e-b7f6-47ca-97a5-98f41170794b)

Sir, I'm trying but not getting exactly where there is an issue because that URL is right.

**Comment by dipesh-17** [comment]
@NirajD10

**Comment by NirajD10** [comment]
you are facing issue "/admin/dashboard" path and couldn't found (404). You need check yourself if path trace available or not. check on postman with include authorization token if it's working or not.

**Comment by dipesh-17** [comment]
![error_07-01](https://github.com/NirajD10/pureplantparadise/assets/75944150/983b8bb7-c3e6-4cac-8ee8-e1218849c8e6)


I'm trying to update settings but i'm getting this error i think shop-settings file is not there I checked

**Comment by Abhi865625** [comment]
@dipesh-17 If you are trying to access the admin dashboard without having any paid order then you have to edit the adminShopRead.js inside getDashbord add this condition. I have attached the screenshot for your reference.

if (totalRevenueandSales.length === 0) {
      return res.status(200).json({
        totalRevenue: 0,
        totalSales: 0,
        totalOrders: 0,
        totalCustomers: 0,
        permonthSaleOrder: [],
      });
    }
    
![WhatsApp Image 2024-05-07 at 8 34 41 PM](https://github.com/NirajD10/pureplantparadise/assets/93569162/a7f45034-9f91-4069-9207-54a764c2630a)

**Comment by NirajD10** [comment]
> I'm trying to update settings but i'm getting this error i think shop-settings file is not there I checked

@dipesh-17 what do you mean by shop settings file? if you are talking about shop-settings controller, please check adminShopActions.js under putShopSettings function. 

I think you didn't understand MVC architecture as well as project. please understand code carefully before asking issues.

The issue was faced 401 status code as Unauthorized(Not allowed) you must have super-admin roles in order to access edit, write of admin site. if it's then you should clear cache browser and login in again.

**Comment by dipesh-17** [comment]
@Abhi865625 Thank you for this function now it's working, as you mentioned totalamount looking for somevalue that's why I'm facing issue with admin/dashboard.

@NirajD10 Yeah, I agree with you, I'm new to Mern stack and learning from your project so this is new for me but as per your guidance I had added an admin account but it's saying Unauthorized(Not allowed)

![image](https://github.com/NirajD10/pureplantparadise/assets/75944150/dce5e550-f433-43e0-9e3e-e38e472d6a2b)

**Comment by NirajD10** [comment]
> @Abhi865625 Thank you for this function now it's working, as you mentioned totalamount looking for somevalue that's why I'm facing issue with admin/dashboard.
> 
> @NirajD10 Yeah, I agree with you, I'm new to Mern stack and learning from your project so this is new for me but as per your guidance I had added an admin account but it's saying Unauthorized(Not allowed)

have you tried clear cache and login again?

**Comment by dipesh-17** [comment]
@NirajD10 Yes, I have tried that also but no change 
![image](https://github.com/NirajD10/pureplantparadise/assets/75944150/6ff2e8ae-89d6-454f-975d-4c82766d551b)
I may not have full knowledge of MVC architecture so I'm not getting where the exact issue is.

![image](https://github.com/NirajD10/pureplantparadise/assets/75944150/67b26486-5c0b-4772-aeb7-49f5d797ca5e)

**Comment by NirajD10** [comment]
> @NirajD10 Yes, I have tried that also but no change ![image](https://private-user-images.githubusercontent.com/75944150/329134753-6ff2e8ae-89d6-454f-975d-4c82766d551b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NzAyNTYsIm5iZiI6MTcxNTY2OTk1NiwicGF0aCI6Ii83NTk0NDE1MC8zMjkxMzQ3NTMtNmZmMmU4YWUtODlkNi00NTRmLTk3NWQtNGM4Mjc2NmQ1NTFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA2NTkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExYWEzYmVkMGNjMDIxNDlhYmY4YzBjODA5Y2YwM2RmNWRlZjUxNjg5MjU2YzcyY2NlNzZhMjAzZmM3ZDhiNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.66OFfZ9yWrbd1VyPDU1x1VuXbxxFzXi4_J7TL2W-RvM) I may not have full knowledge of MVC architecture so I'm not getting where the exact issue is.

if you want to know where the authorization came. You should visit **middleware** folder from backend and find _is-admin-auth.js_ file. 

The issue you are facing is that while sending a request it may need "Authorization" but it wouldn't found it.
